Repository TakingITGlobal/commit2act, pull requests merged in 2024-01, with the labels that each got.

#85 TIG-549 makes sure that filters are updated when a different tab is s…
  src/components/GlobalLeaderboard.js
Labels: bug

#86 [TIG-498] Restore App test(s)
  package.json
  src/App.test.js
  src/components/logAction/ActionFact.js
  src/utils/mock-redux-store-provider.js
Labels: testing

#87 [TIG-505] Configure CI with React app tests
  .github/workflows/react-app.yml
  mock-aws-exports.txt
  package.json
  src/App.js
  src/App.test.js
Labels: testing

#91 [TIG-512] Simple startup doc
  docs/GettingStarted.md
  package.json
Labels: testing, lint

#94 [TIG-499, TIG-502] Setup jest-axe tests and jsx-a11y linter
  .eslintrc.json
  .github/workflows/react-app-ci.yml
  package-lock.json
  package.json
  src/App.test.js
  src/setupTests.js
  src/views/AppNav.js
  src/views/AppNav.test.js
Labels: a11y, testing, lint

#96 [TIG-570] Donut charts rendering
  src/components/UserStatsCharts.js
  src/components/groupProfile/GroupPageLeaderboard.js
  src/hooks/use-user-stats.js
Labels: bug
