Repository TakingITGlobal/commit2act, pull requests merged in 2024-02, with the labels that each got.

#97 [TIG-587] ESLint auto-fix and top-level overrides removed
  .eslintrc.json
  src/App.js
  src/components/.eslintrc.json
  src/components/adminDashboard/QuizCard.js
  src/components/authentication/Login_material.js
  src/components/contexts/LanguageContext.js
  src/index.js
  src/localization/index.js
  src/pages/.eslintrc.json
  src/prop-types/component.js
  src/utils/mock-redux-store-provider.js
  src/views/AppNav.js
  src/views/pageContainer/PageContainer.js
  src/views/pageContainer/PrivateRoute.js
Labels: lint

#98 [TIG-500] Page level tests
  src/App.js
  src/components/GlobalLeaderboard.js
  src/components/UserActions.js
  src/components/adminDashboard/BarChart.js
  src/components/adminDashboard/Dashboard.js
  src/components/adminDashboard/LineChart.js
  src/components/validateActions/ActionNameSearchBar.js
  src/components/validateActions/GroupNameSearchBar.js
  src/components/validateActions/MyGroupsPanel.js
  src/pages/AccountSettings.js
  src/pages/AccountSettings.test.js
  src/pages/Actions.test.js
  src/pages/AdminDashboard.test.js
  src/pages/ValidateActions.js
  src/pages/ValidateActions.test.js
  src/setupTests.js
  src/utils/jest-mock-utils.js
  src/views/AppNav.js
  src/views/AppNav.test.js
Labels: a11y, testing

#101 Tig 74 improved mobile nav
  public/assets/images/icon-plus.png
  src/components/LanguageHandler.js
  src/components/Navbar.js
  src/components/authentication/LoginNavbar.js
  src/localization/en.js
  src/localization/fr.js
  src/styles/page-container.js
  src/views/AppNav.js
  src/views/pageContainer/PageContainer.js
Labels: enhancement

#102 Some temporary fixes for a drawer/container issue
  src/components/Navbar.js
  src/pages/Landing.js
  src/styles/page-container.js
  src/views/pageContainer/PageContainer.js
Labels: bug
